# GitHub Actions Workflow with MATLAB Actions

# Copyright 2021-2022 The MathWorks, Inc.

name: MATLAB R2021a, 21b, 22a Builds

on:
  push:
    branches: [ R2021a ]

  pull_request:
    branches: [ R2021a ]

jobs:
  matlab-job-22a:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2022a

      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: openProject(pwd); HEVProject_runtests;

  matlab-job-21b:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2021b

      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: openProject(pwd); HEVProject_runtests;

  matlab-job-21a:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2021a

      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: openProject(pwd); HEVProject_runtests;
